### ISSUE TITLE
Visualización de la capa de puntos para cada paisaje

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#1]

**Comment by padawannn** [comment]
De momento lo hacemos sin torque y más adelante se lo añadimos

**Comment by isapozuelo** [comment]
@padawannn 
¿Para cada paisaje te refieres a que suba una capa por categoría? o ¿está bien así?
https://gipc-admin.carto.com/viz/4aae6b3e-58a4-11e6-afa9-0e3a376473ab/map

**Comment by padawannn** [comment]
Así está perfecto, solo faltan los destacados
