### ISSUE TITLE
Pantalla de descripción corta de un paisaje

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#11]
La pantalla de descripción corta de un paisaje cambia un poco vamos a añadir algunos atributos en forma de hashtag pero que no sean clicables. Habla con @isapozuelo para que te lo explique bien.

**Comment by javigil-geo** [comment]
![gipc aplicacion web-04](https://cloud.githubusercontent.com/assets/19855697/17335193/66c5c292-58d9-11e6-8c8e-4dcab3e252e5.png)
