### ISSUE TITLE
Diseñar la pantalla de storytelling

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#12]
@javigil-geo habla con @isapozuelo para que te diga los datos que tienen que ir en esta pantalla

**Comment by javigil-geo** [comment]
Pantalla Storytelling:
https://drive.google.com/open?id=0B0UH4LXpUE0YN25yZk9Sa3I5Vk0

Con vídeo cargado:
https://drive.google.com/open?id=0B0UH4LXpUE0YRUdDUWhRM2QxUmc
