### ISSUE TITLE
Diseñar pantalla de paisaje tipo línea y tipo mapa

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#13]
- Tipo linea:
  En lugar de tener un mapa de fondo tenemos un video reproduciéndose y cuando pinchas sobre un punto de la linea empieza a reproducirse otro video. @isapozuelo te puede pasar un video de ejemplo. A ver como hacemos para que convivan bien el video y la linea con puntos y como hacemos la transición entre videos. Lo hablamos cuando te vayas a poner.
- Tipo mapa:
  Se pinta un polígono sobre un mapa de fondo y cuando pinchas sobre un punto se empieza a reproducir un video o un sonido.

Si consideras que no hace falta psd te sientas conmigo y lo vemos

**Comment by javigil-geo** [comment]
Tipo Línea:
1: https://drive.google.com/open?id=0B0UH4LXpUE0Ya2QzY1M1ZHRHSjQ
2: https://drive.google.com/open?id=0B0UH4LXpUE0YNlJ2VXlSWVc5MUU
3: https://drive.google.com/open?id=0B0UH4LXpUE0YVF8xZS1oV09HYzA
4: https://drive.google.com/open?id=0B0UH4LXpUE0YV1NpQTZMY2pwS1k

Tipo mapa:
1: https://drive.google.com/open?id=0B0UH4LXpUE0YYkdIZGhnZlpVUEk
2: https://drive.google.com/open?id=0B0UH4LXpUE0YcTM4ekIzVXF6bVU
3: https://drive.google.com/open?id=0B0UH4LXpUE0YamVRT0hwaGtyRHM
4: https://drive.google.com/open?id=0B0UH4LXpUE0YNUVMSm1LTHhFVmc
5: https://drive.google.com/open?id=0B0UH4LXpUE0YUkZGLURpYjBZdUU
