### ISSUE TITLE
Diseñar Footer histórico

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#14]
La capa de organización territorial debe ser una especie de footer que represente periodos históricos donde tu selecciones el periodo histórico que quieres ver (sólo puedes seleccionar uno)

¿ @isapozuelo la web se carga con una capa de organización territorial por defecto ?

**Comment by javigil-geo** [comment]
![gipc aplicacion web-07](https://cloud.githubusercontent.com/assets/19855697/17335116/1ee11954-58d9-11e6-9238-505a77a8ca21.png)
