### ISSUE TITLE
Diseñar panel de filtros

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#15]
Vamos a tener un panel de filtros al estilo de la iucn http://www.iucn-medmis.org/
donde se mostrarán los tipos de asentamiento, infraestructuras, etc.

Por defecto aparece todo marcado

**Comment by javigil-geo** [comment]
![gipc aplicacion web-05](https://cloud.githubusercontent.com/assets/19855697/17335077/fe1dbb14-58d8-11e6-9b34-eb86955ea5fa.png)

**Comment by javigil-geo** [comment]
Carpeta PSD de los pantallazos:
https://drive.google.com/open?id=0B0UH4LXpUE0YVllwTFJuYUg2cmM
