### ISSUE TITLE
Conseguir imágenes de los paisajes

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#17]
Antes que nada dime el nombre de la red social donde están las imágenes de los paisajes para ver si tiene una api para consumirlas. Si no encuentro api:

Me da muy mal rollo consumir las imágenes de una red social. Tenemos que conseguir todas las imágenes (pídelas al cliente o pon a un becario a descargarlas, lo que tu consideres más rápido).

Cuando tengamos todas la imágenes hay que meter su nombre en la base de datos y las subiremos a amazon s3

**Comment by isapozuelo** [comment]
Aquí tienes las imágenes descargadas. @padawannn Avísame cuándo estén en S3 para poder incluir la URL de cada IMG en la base de datos.

https://drive.google.com/drive/u/0/folders/0B8E-_zSwmuI_LVhTdXdCLURaeEk

**Comment by padawannn** [comment]
No hace falta, si cada imagen tiene como nombre el ID del paisaje no hace falta meterla en base de datos. Si esto es así ponme en review la tarea plis

**Comment by isapozuelo** [comment]
Sí, cada imagen tiene ID.jpg

**Comment by padawannn** [comment]
Para la próxima acuérdate de quitar la etiqueta de inprogress
