### ISSUE TITLE
Diseñar popup genéricos

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#19]
Necesitamos un estilo genérico de popup para las capas que no son de paisajes. Nada de florituras, mira el popup que sale en esta visualización 

https://gipc-admin.carto.com/viz/d5b30104-598f-11e6-a374-0e3ff518bd15/public_map

y rediseña un poco el contenido.

**Comment by javigil-geo** [comment]
https://drive.google.com/open?id=0B0UH4LXpUE0YSExDR0xqUTJ6alU

Organización Territorial: #6636a3
Espacios Protegidos Naturales: #56cf9b
Camino de Santiago: #d6516b
Vía Pecuaria: #aedd64
Ruta de la Plata: #90fcf1
Calzada Romana: #ffc571

**Comment by javigil-geo** [comment]
Botones cerrar de popup:

Organización Territorial:
https://drive.google.com/open?id=0B0UH4LXpUE0Yb0NxUDAwOXYwX0E

Espacio Naturales Protegidos:
https://drive.google.com/open?id=0B0UH4LXpUE0YZWFTQ0JNTkpOREU

Camino Santiago:
https://drive.google.com/open?id=0B0UH4LXpUE0YMHJVMjZsR2kxZjA

Calzada romana:
https://drive.google.com/open?id=0B0UH4LXpUE0YZTVKT3F5UUVlWGc

Ruta de la Plata:
https://drive.google.com/open?id=0B0UH4LXpUE0YbUltNFh5RGlwdE0

Vía pecuaria:
https://drive.google.com/open?id=0B0UH4LXpUE0YcFhoLUU4SGFxNVk
