### ISSUE TITLE
Visualización para la capa de espacios protegidos

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#2]
Si me falta alguno o están incorrectos modifícalos @isapozuelo, me baso de momento en tu documento:
- [ ] Espacios Naturales Protegidos
- [ ] Ramsar
- [ ] LIC
- [ ] Parque Nacional
- [ ] Reserva biosfera
- [ ] ZEPA

En esta visualización acuérdate de definir el popup con los atributos que queremos que se muestren.

**Comment by isapozuelo** [comment]
@padawannn He actualizado la denominación que has puesto arriba (tan solo cambiar algunas mayúsculas). 

¿Necesitas que ponga por encima los puntos de los paisajes?

Falta que ellos me pasen los datos de los nombre de los paisajes, ya se lo he pedido. Cuándo me la pasen hago un UPDATE al dataset.

https://gipc-admin.carto.com/viz/05d867e2-5a22-11e6-aa4f-0e05a8b3e3d7/public_map

**Comment by padawannn** [comment]
Perfecto Isa.

PD:  No hace falta que no pongas los puntos
