### ISSUE TITLE
Visualización de sistemas lineales

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#3]
Si me falta alguno o están incorrectos modifícalos @isapozuelo, me baso de momento en tu documento:
- [ ] Calzada 
- [ ] Camino de Santiago
- [ ] Ruta de la plata
- [ ] Via pecuaria

En esta visualización acuérdate de definir el popup con los atributos que queremos que se muestren.

**Comment by isapozuelo** [comment]
Sistemas lineales:
https://gipc-admin.carto.com/viz/5b21585e-5990-11e6-8026-0e3ff518bd15/map

Buffer 20 km:
https://gipc-admin.carto.com/viz/74de9e62-5fcd-11e6-8df3-0e05a8b3e3d7/map

Buffer 40 km:
https://gipc-admin.carto.com/viz/c13240e8-5fcd-11e6-a625-0ecd1babdde5/map
