### ISSUE TITLE
Capas de organización territorial

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#4]
Si me falta alguno o están incorrectos modifícalos @isapozuelo, me baso de momento en tu documento. Cada checkbox es una visualización individual y si checkboxes
- [x] Prerromanos 
- [x] Dominio cartaginés
- [x] 197 AC
- [x] Siglo VI
- [x] 814
- [x] 1210
- [x] 1360
- [x] 1715
- [x] 1833

**Comment by isapozuelo** [comment]
- [x]  Prerromanos

https://gipc-admin.carto.com/viz/d5b30104-598f-11e6-a374-0e3ff518bd15/map
- [x]  Dominio cartaginés

https://gipc-admin.carto.com/viz/dd4934dc-5990-11e6-a069-0ecd1babdde5/map
- [x]  197 AC

https://gipc-admin.carto.com/viz/8a447d74-598f-11e6-9ef8-0ecd1babdde5/map
- [x]  Siglo VI
  https://gipc-admin.carto.com/viz/6a173352-598f-11e6-abad-0e05a8b3e3d7/map
- [x]  814
  https://gipc-admin.carto.com/viz/31256562-5991-11e6-9d0d-0e3ff518bd15/map
- [x]  1210
  https://gipc-admin.carto.com/viz/057e6378-5991-11e6-a78a-0e3ebc282e83/map
- [x]  1360
  https://gipc-admin.carto.com/viz/f2ba1f96-598d-11e6-8d23-0e3ebc282e83/map
- [x]  1715
  https://gipc-admin.carto.com/viz/84c23e52-5991-11e6-bfe1-0e3ebc282e83/map
- [x]  1833
  https://gipc-admin.carto.com/viz/38f8f0fc-5990-11e6-b303-0ecd1babdde5/map

**Comment by padawannn** [comment]
@isapozuelo falta editar el popup, es decir, para todas las visualizaciones de este tipo vamos a usar el popup de la visualización. Ahora mismo cuando pinchas en el popup sale 

SUBCATEGOR
Indoeuropeos

Hay que cambiar ese label para que en lugar de poner SUBCATEGOR ponga un título más informativo. Esto hay que hacerlo para todas las visualizaciones menos la de paisajes
Por el estilo del popup no te preocupes, lo único que necesito es que el popup muestre la información correcta.

PD: Acuérdate de poner las tareas en review (veo muchas visualizaciones acabadas) o si falta algo para no poder ponerla en ese estado especificarlo en la tarea.

**Comment by isapozuelo** [comment]
Hecho. Si no encaja como lo he hecho con el diseño me decís.
