### ISSUE TITLE
Diccionario de columnas

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#5]
@isapozuelo me tienes que pasar un diccionario que relacione cada columna de la tabla paisajes con su atributo

**Comment by isapozuelo** [comment]
@padawannn  Esta tabla es el diccionario de atributos: 
- "name_column" es el nombre que tiene la columna en la tabla original
- "Description" es el alias que queremos que se visualice en la aplicación.
https://gipc-admin.carto.com/tables/diccionario_paisajes

Esta tabla sirve para agrupar los atributos de la tabla paisajes por las categorías que van en el filtro avanzado de los paisajes
https://gipc-admin.carto.com/tables/diccionario_atributos

**Comment by isapozuelo** [comment]
@padawannn ya hemos arreglado la tabla. En una sola tabla están las dos cosas:
https://gipc-admin.carto.com/tables/diccionario_paisajes
- "name_column" es el nombre que tiene la columna en la tabla original
- "Description" es el alias que queremos que se visualice en la aplicación.
- "Grupo" las categorías en las que se agrupan los atributos en el filtro avanzado. Hay columnas que no irían al filtro (por ejemplo, el nombre del paisaje, la comunidad autónoma, etc.) en esos casos, la columna grupo está a NULL.
