### ISSUE TITLE
Crea tabla de polígonos para los paisajes tipo Mapa

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#7]
Esta tabla se tiene que relacionar con la tabla de paisajes

**Comment by isapozuelo** [comment]
La clave primaria de la tabla de paisajes es la columna que se llama 'numero'
Se relaciona con esta tabla a través de la columna 'paisaje_id'

https://gipc-admin.carto.com/tables/modo_mapa_polygon
