### ISSUE TITLE
Visualización para los paisajes tipo línea

### ISSUE THREAD

**Issue by padawannn** [GeographicaGS/gipc#9]
Son dos capas, la línea y los puntos encima. @isapozuelo prepara la visualización y después hablaremos con @josegilg para que la mejore

**Comment by isapozuelo** [comment]
https://gipc-admin.carto.com/viz/5b21585e-5990-11e6-8026-0e3ff518bd15/public_map

**Comment by isapozuelo** [comment]
https://gipc-admin.carto.com/viz/60d98a04-62fb-11e6-8897-0e233c30368f/map
